export default [
  'Opel Astra',
  'Honda',
  'Porsche Macan',
  'Volkswagen Polo',
  'Hyundai Elantra',
  'Geely Atlas',
  'Lada Vesta',
  'Renault Captur',
  'Peugeot 208',
  'Toyota Corolla',
  'BMW X3',
  'Ford Focus',
  'Mercedes E-Class',
  'Audi A4',
  'Nissan Sentra',
  'Chevrolet Malibu',
  'Subaru Impreza',
  'Mazda CX-9',
  'Kia Rio',
  'Volvo S60',
  'Tesla  Model X',
  'Lamborghini Aventador',
  'Ferrari Portofino',
  'Jaguar F-PACE',
  'Rolls-Royce Ghost',
  'Bentley Continental GT',
  'Aston Martin DB11',
  'McLaren 720S',
  'Maserati Ghibli',
  'Bugatti Chiron',
  'Alfa Romeo Giulia',
  'Lexus ES',
  'Infiniti Q50',
  'Land Rover Discovery',
];
